
name: Publish Package

on:
  workflow_dispatch:
    
jobs:
  Publish:
    name: Publish Package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
        with:
          nuget-api-key: ${{secrets.NUGET_KEY}}
          
      - name: Restore (For Some Reason)
        run: nuget restore OuterWildsModTemplate.csproj

      - name: Pack Template
        run: nuget pack OuterWildsModTemplate.csproj -Build -NonInteractive
      
      - name: Upload Package
        run: nuget push Bwc9876.OuterWildsModTemplate.*.nupkg
